name: Security & Dependencies

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  # Dependency updates
  dependency-updates:
    name: Check for Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: |
          echo "📦 Checking for outdated packages..."
          npm outdated || echo "All packages are up to date"
          
          echo "🔒 Checking for security vulnerabilities..."
          npm audit --audit-level=moderate || echo "No security issues found"

      - name: Create issue for updates
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔒 Security & Dependency Updates Available';
            const body = `## 📦 Dependency Updates Available
            
            Some packages have updates available. Please review and update:
            
            ### 🔍 To check for updates:
            \`\`\`bash
            npm outdated
            npm audit
            \`\`\`
            
            ### 🚀 To update packages:
            \`\`\`bash
            npm update
            npm audit fix
            \`\`\`
            
            ### ⚠️ Important Notes:
            - Test thoroughly after updates
            - Check breaking changes in major version updates
            - Run full test suite after updates
            - Update lock file if needed
            
            ---
            *This issue was automatically created by the security workflow.*`;
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['dependencies', 'security']
            });
            
            const existingIssue = issues.data.find(issue => 
              issue.title === title
            );
            
            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['dependencies', 'security', 'automated']
              });
            }

  # Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          echo "🔒 Running security audit..."
          npm audit --audit-level=moderate
          
          echo "📋 Generating security report..."
          npm audit --json > security-report.json

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.json
          retention-days: 30

      - name: Comment on security issues
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🚨 Security Issues Detected
            
            ### ⚠️ Security vulnerabilities found in dependencies
            
            Please run \`npm audit\` to see details and \`npm audit fix\` to resolve.
            
            ### 🔍 Manual Check:
            \`\`\`bash
            npm audit --audit-level=moderate
            npm audit fix
            \`\`\`
            
            ### 📋 Security Report:
            A detailed security report has been uploaded as an artifact.
            
            ---
            *This comment was automatically created by the security workflow.*`;
            
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }

  # CodeQL security analysis
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  # Container security scanning
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    needs: [dependency-updates]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t scoreboard-api:security-scan .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scoreboard-api:security-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
